  steps:
  # Build the container image
  - name: 'eu.gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}', '.']
  # Push the container image to Container Registry
  - name: 'eu.gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}']
  # Deploy container image to Cloud Run
  - name: 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${REPO_NAME}'
    - '--image'
    - 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}'
    - '--region'
    - '${LOCATION}'
    - '--cpu'
    - '1'
    - '--max-instances' 
    - '1'
    - '--cpu-throttling'
  images:
  - 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}'
